language: cpp
sudo: required

matrix:
  include:
    # 1/ OSX GCC7 PYTHON3.6 build
    - os: osx
      compiler: gcc-7
      env:
        - PYTHON=3.6
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'
        - Fortran_COMPILER='gfortran'
        - BUILD_TYPE='Release'
        - PYTHON='--three'
        - COVERAGE=OFF
    # 2/ OSX GCC7 PYTHON2.7 build
    - os: osx
      compiler: gcc-7
      env:
        - PYTHON=2.7
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'
        - Fortran_COMPILER='gfortran'
        - BUILD_TYPE='Release'
        - PYTHON='--three'
        - COVERAGE=OFF
    # 3/ Linux GCC7 PYTHON3.6 build
    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake3
            - g++-7
            - gcc-7
            - gfortran-7
            - lcov
            - swig
      env:
        - PYTHON=3.6
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'
        - Fortran_COMPILER='gfortran-7'
        - BUILD_TYPE='Debug'
        - PYTHON='--three'
        - COVERAGE=ON
    # 4/ Linux GCC7 PYTHON2.7 build
    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake3
            - g++-7
            - gcc-7
            - gfortran-7
            - lcov
            - swig
      env:
        - PYTHON=2.7
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'
        - Fortran_COMPILER='gfortran-7'
        - BUILD_TYPE='Debug'
        - PYTHON='--three'
        - COVERAGE=ON

cache:
  directories:
    - $HOME/.local

before_install:
  - pip install --upgrade pip
  - sudo pip install -U --only-binary=numpy,scipy numpy scipy

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update &> /dev/null
      brew cask uninstall --force oclint
      brew upgrade cmake python
      brew install gcc@7 pipenv swig
      softwareupdate --list
      softwareupdate --install "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4"
    elif [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      chmod +x scripts/install_cmake.sh
      sudo ./scripts/install_cmake.sh
    fi

before_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-7 -D CMAKE_CXX_COMPILER=g++-7 ..

script:
  - make
  - make test
  - make python
  - make pythontest
