name: Ubuntu CI

on:
  pull_request:
  push:

jobs:
  gcc8-build:
    name: GCC8 build
    strategy:
      matrix:
        python-version: ["3.7.5"]
        os: ["ubuntu-self-hosted"]
    runs-on: ${{ matrix.os }}
    env:
      CXX_COMPILER: "/usr/lib/ccache/g++"
      C_COMPILER: "/usr/lib/ccache/gcc"
      PYTHON: ${{ matrix.python-version }}
      COVERAGE: "ON"
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install ccache
        run: sudo apt install ccache

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Install Python dependencies
        run: pip install -U --only-binary=numpy,scipy numpy scipy openfermion

      - name: Install qulacs for Ubuntu
        run: ./script/build_gcc.sh
        if: ${{ contains(matrix.os, 'ubuntu') }}

      - name: Install qulacs Python module
        run: python setup.py install

      - name: Test in Ubuntu
        run: |
          cd ./build
          make test
          make pythontest
        if: ${{ contains(matrix.os, 'ubuntu') }}

  nvcc-gcc8-GPUbuild:
    name: nvcc + gcc8 build
    strategy:
      matrix:
        python-version: ["3.7.5"]
    runs-on: ["ubuntu-self-hosted"]
    env:
      CXX_COMPILER: "g++-8"
      C_COMPILER: "gcc-8"
      PYTHON: ${{ matrix.python-version }}
      COVERAGE: "ON"
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Python dependencies
        run: pip install -U --only-binary=numpy,scipy numpy scipy openfermion

      - name: Install qulacs for Ubuntu
        run: ./script/build_gcc_with_gpu.sh
        if: ${{ contains(matrix.os, 'ubuntu') }}

      - name: Install qulacs Python module
        run: python setup.py install

      - name: Test in Ubuntu
        run: |
          cd ./build
          make test -j
          make pythontest -j
        if: ${{ contains(matrix.os, 'ubuntu') }}

  source-dist:
    name: Source dist
    needs: gcc8-build
    strategy:
      matrix:
        python-version: ["3.7.5"]
    runs-on: "ubuntu-self-hosted"
    env:
      TWINE_USERNAME: "__token__"
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD_QULACS }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Run sdist
        run: python setup.py sdist

      - name: Uplead the source if the Git tag is set
        run: |
          python -m pip install twine
          python -m twine upload dist/*
        # This condition is refered for:
        #   https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
        if: ${{ contains(github.ref, '/tags/') }}

  source-dist-gpu:
    name: Source dist (Qulacs-GPU)
    needs: gcc8-build
    strategy:
      matrix:
        python-version: ["3.7.5"]
    runs-on: "ubuntu-self-hosted"
    env:
      TWINE_USERNAME: "__token__"
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD_QULACS_GPU }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Switch setup.py to GPU enabled version
        run: cp setup_gpu.py setup.py

      - name: Run sdist
        run: python setup.py sdist

      - name: Uplead the source if the Git tag is set
        run: |
          python -m pip install twine
          python -m twine upload dist/*
        # This condition is refered for:
        #   https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
        if: ${{ contains(github.ref, '/tags/') }}

  format:
    name: Format with clang-format
    strategy:
      matrix:
        os: ["ubuntu-self-hosted"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Install qulacs for Ubuntu
        run: ./script/build_gcc.sh

      - name: Run clang-format
        run: cmake --build build --target format

      - name: Compare diff
        run: |
          diff=$(git diff)
          echo $diff
          test $(echo -n $diff | wc -l) -eq 0
