name: macOS CI

on:
  push:
  pull_request:

jobs:
  gcc10-build:
    name: GCC10 build
    strategy:
      matrix:
        python-version: ["3.7.5"]
    runs-on: "macos-11"
    env:
      CXX_COMPILER: "/usr/local/opt/ccache/libexec/g++-8"
      C_COMPILER: "/usr/local/opt/ccache/libexec/gcc-8"
      PYTHON: ${{ matrix.python-version }}
      COVERAGE: "ON"
      CACHE_NAME: "ccache-qulacs-build-v2"
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install ccache
        run: brew install ccache

      - name: Install Python dependencies
        run: pip install -U --only-binary=numpy,scipy numpy scipy openfermion

      - name: Install Boost for macOS
        run: |
          brew upgrade
          brew install boost
          brew link boost

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}

      - name: Install qulacs for macOS
        run: ./script/build_gcc.sh

      - name: Install qulacs Python module
        run: python setup.py install

      - name: Test in macOS
        run: |
          cd ./build
          make test -j
          make pythontest -j

      - name: Show cache stats
        run: ccache -s -v
