name: macOS CI

on:
  push:
  pull_request:

jobs:
  gcc8-build:
    name: GCC8 build
    strategy:
      matrix:
        python-version: ["3.7.5"]
        os: ["macos-latest"]
    runs-on: ${{ matrix.os }}
    env:
      CXX_COMPILER: "/usr/local/opt/ccache/libexec/g++-11"
      C_COMPILER: "/usr/local/opt/ccache/libexec/gcc-11"
      PYTHON: ${{ matrix.python-version }}
      COVERAGE: "ON"
      CACHE_NAME: "ccache-qulacs-build"
    # TODO: remove this comment
    # The following steps assume that ccache is already installed in a machine for CI.
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install ccache
        run: brew install ccache

      - name: Install Python dependencies
        run: pip install -U --only-binary=numpy,scipy numpy scipy openfermion

      - name: Workaround for OpenMP link error on mac
        # In GitHub Actions virtual environment macos-10.15/20201115.1,
        # linking some functions from libgomp fails since the linker cannot find
        # some library files from gcc-8 installed via Homebrew.
        # The following command fixes this issue by (brew) re-linking files from gcc-8.
        # cf. https://stackoverflow.com/a/55500164
        run: brew link --overwrite gcc@11

      - name: Install Boost for macOS
        run: |
          brew upgrade
          brew install boost
          brew link boost

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}

      - name: Install qulacs for macOS
        run: ./script/build_gcc.sh

      - name: Install qulacs Python module
        run: python setup.py install

      - name: Test in macOS
        run: |
          cd ./build
          make test -j
          make pythontest -j

      - name: Show cache stats
        run: ccache -s -v
